### ISSUE TITLE
Original repo

### ISSUE THREAD

**Issue by ZyphenVisuals** [atariandante/now-listening#1]
Hi! Zyphen here.

Does this repo have any modifications to my original code? I'd like to upload it to my own repo if possible, so I'd appreciate if you could fork from there with the changes you want to make.

Sorry to suddenly step in like this. I sincerely just forgot to make a repo for it originally, since I didn't expect it to become kind of popular 😅

**Comment by atariandante** [comment]
Hey! What a pleasure to meet you, no, I didn't modify the original code. I can't do the chances right now, but probably this weekend I will if that sounds good to you.

I wonder how you find it, haha. Cheers.

**Comment by ZyphenVisuals** [comment]
Thank you!

It actually comes up when you search "Zyphen's now playing" :)

I've already created the official repo, and just kind of hope that one will be recommended instead of this one, since I'll be able to update it directly.

Thanks for all your help, I'll close this issue now!
